name: Mannayo Front

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          # cache: 'npm'

      - name: Set ENV
        run: |
          echo "${{ secrets.SECRET_ENV }}" | base64 --decode > .env
          find src

      - run: npm ci --legacy-peer-deps
      - run: npm run build
        env:
          CI: false

      - name: Deploy Prod use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: './dist'
          target: '/home/ubuntu/deploy_front'
          strip_components: 2

      - name: Transfer Deploy Script use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "deploy.sh"
          target: "/home/ubuntu/deploy_front"
      
      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: chmod +x /home/ubuntu/deploy_front/deploy.sh && sh /home/ubuntu/deploy_front/deploy.sh